* writing-utils
Some small tools making editing, writing articles (especially blog articles) more conveniently in Emacs.
* Installation
Clone this repo and add path, then =require= packages you want:

#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path "~/.emacs.d/lisp/writing-utils/")
(require 'writing-utils)
(require 'minibuffer-enhancements)
(require 'page-title)
(require 'flickr)
(require 'markdown-toc)
(require 'markdown-and-html)
#+END_SRC

* Packages list
** writing-utils.el
*** Manipulate Line
- =M-up/down= to move current line up/down.
- =C-c d l= to duplicate current line.
- =C-c M-w= to copy current line into kill-ring.

*** Programming Related
- =C-a= to back to indentation first.
  #+BEGIN_SRC emacs-lisp
  ;; only in programming-related mode:
  (define-key prog-mode-map (kbd "C-a") 'beginning-of-line-or-indentation)
  ;; or in a global way:
  (global-set-key (kbd "C-a") 'beginning-of-line-or-indentation)
  #+END_SRC

- =M-x indent-buffer= to indent the whole buffer (by current syntax).
- =C-c i M-;= to insert a commented seperator in code like this:
  #+BEGIN_EXAMPLE
  # ======================================================
  # Title: the commented seperators
  # ======================================================
  #+END_EXAMPLE
- =C-c i p= to insert a file path.

*** Count Words
- =M-x wc= to count English/Japanese/Chinese characters and words, *except for comments, org document options/attributions*.

** minibuffer-enhancements.el
- =C-a= twice to erase minibuffer, without kill-ring pollution.
- =M-<backspace>= to delete path back to parent directory, without the pollution to kill-ring.
- =<backtab> (Shift-tab)= to jump into =*Completions*= buffer forcely.
** flickr.el
=C-c i f= in markdown/org/html-mode to retrieve, format and insert flickr photo raw link conveniently.

#+BEGIN_QUOTE
Notice: This function currently cannot retrieve your private photos.
#+END_QUOTE

** page-title
- One key =C-c i l= to retrieve the title of HTML file via its URL, and insert to:
    - Markdown file.
    - Org file.
    - HTML file.
    - =twittering-mode= buffer.

** hexo.el
This has been splited as an independent package. See [[https://github.com/kuanyui/hexo.el][hexo.el]].
** html-entities-convert.el
library to convert html entities. e.g. ="&gt;" → ">"=

** markdown-toc.el
Generate TOC (Table of Contents) with inline CSS styled for markdown file:
- =M-x markdown-toc-insert= Generate and insert/update TOC for current article.
- =M-x markdown-toc-remove= Remove TOC.

You can customize style like this:
#+BEGIN_SRC emacs-lisp
(setq markdown-toc-header-and-footer-html
  ["<div id=\"text-table-of-contents\" style='background-color:*f0f0f7;border-left:5px solid *568DBE;padding:10px 20px;margin:1em 0;display:table;'><h3 style='color:*505050;margin-top:10px !important;'>Contents</h3>"
   "</div>"])
#+END_SRC

** markdown-and-html.el
#+BEGIN_QUOTE
The name and usage of this package are still not determined ˊ・ω・ˋ.
#+END_QUOTE

- =M-x html-insert-strike= (or =C-c i s= in markdown-mode) to insert =<strike>text</strike>=.

* License
WTFPL 2.0

kuanyui (ɔ) Copyleft 2014

This program is free software. It comes without any warranty, to the extent permitted by applicable law. You can redistribute it and/or modify it under the terms of the Do What The Fuck You Want To Public License, Version 2, as published by Sam Hocevar. See http://www.wtfpl.net/ for more details.
